n = input('Digite algo: ')
print(f'O tipo primitivo dessa valor é {type(n)}')
print('Só tem espaços?', n.isspace())
print('É númerico?', n.isnumeric())
print('É alfabético? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())
print('Está em maiúsculas? ', n.isupper())
print('Está em minúsculas? ', n.islower())
print('Está capitalizada? ', n.istitle())

